### ISSUE TITLE
AVX and AVX2 not available in enclaves

### ISSUE THREAD

**Issue by jmechalas** [intel/kvm-sgx#9]
cpuid leaf 0x12, subleaf 0x1 returns the valid bits of SECS.ATTRIBUTES that can be set with ECREATE. The XFRM attributes are set in EDX:ECX, and they control whether or not AVX, AVX2, and FMA are available in an enclave.

On a guest running via KVM, these registers are:
```
$ cpuid -r -l 0x12 -s 0x1
CPU 0:
   0x00000012 0x01: eax=0x00000037 ebx=0x00000000 ecx=0x00000003 edx=0x00000000
```
On the host, these registers are:
```
~$ cpuid -r -l 0x12 -s 0x1
CPU 0:
   0x00000012 0x01: eax=0x00000036 ebx=0x00000000 ecx=0x0000001f edx=0x00000000
```

This looks like a bug. EAX is wrong, and ECX is masking out most extended features.

**Comment by sean-jc** [comment]
Gah, sgx-v4.18.3-r1 intentionally dropped a patch that change the return type of a CPUID related function.  Unfortunately I overlooked a side effect of the patch that swapped the order of two function calls so that the SGX CPUID modifications would run after updating the guest's allowed XCR0.  And this is why patches should only do one thing...

Do you need an update build "now", or can you wait a week or two?  I'm in the process of rewriting the EPC uapi (again), but spinning sgx-v4.19.1-r2 wouldn't be much trouble.

**Comment by jmechalas** [comment]
No rush.

**Comment by jmechalas** [comment]
This may be related to #12, in which case the priority is a bit higher.

**Comment by jmechalas** [comment]
I am going to revise my "no rush" statement. There are not many platforms available today that offer both FLC _and_ AVX instructions, so virtualizing a Xeon E is looking mighty attractive. Would that proposed sgx-v4.19.1-r2 rev still be feasible?

**Comment by sean-jc** [comment]
The new and hopefully improved EPC uapi is ready, although I need to do more testing and cleanup the changelogs.  I should be able to get a release pushed today, early next week at the latest.

**Comment by sean-jc** [comment]
New released pushed.  The AVX bug is fixed, or at least it should be.  Please confirm when you can, absolutely zero rush.

**Comment by jmechalas** [comment]
Confirmed that AVX & family are now showing in enclaves.
